[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8079
  port = 8080
  publish = "dist"
  autoLaunch = false

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"